/*
 * Copyright (C) 2015-2019 Envision Digital Limited
 */

#include <stdlib.h>

const char *iotx_ca_crt = \
{
    "-----BEGIN CERTIFICATE-----\r\n" \
    "MIID2TCCAsGgAwIBAgIJAIxUqZFXyO8oMA0GCSqGSIb3DQEBCwUAMIGCMQswCQYD\r\n" \
    "VQQGEwJDTjERMA8GA1UECAwIU2hhbmdoYWkxETAPBgNVBAcMCFNoYW5naGFpMQ0w\r\n" \
    "CwYDVQQKDARFbk9TMRAwDgYDVQQLDAdFbk9TIENBMRAwDgYDVQQDDAdFbk9TIENB\r\n" \
    "MRowGAYJKoZIhvcNAQkBFgtjYUBlbmlvdC5pbzAeFw0xODExMTkxMDIwMjdaFw0y\r\n" \
    "ODExMTYxMDIwMjdaMIGCMQswCQYDVQQGEwJDTjERMA8GA1UECAwIU2hhbmdoYWkx\r\n" \
    "ETAPBgNVBAcMCFNoYW5naGFpMQ0wCwYDVQQKDARFbk9TMRAwDgYDVQQLDAdFbk9T\r\n" \
    "IENBMRAwDgYDVQQDDAdFbk9TIENBMRowGAYJKoZIhvcNAQkBFgtjYUBlbmlvdC5p\r\n" \
    "bzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANtdO01M5QHAwqalr79b\r\n" \
    "WQEn3rpYeby6vVM92TUmurhL+XsTjVGi0n9LVpW30yaOQ7eACtMwwEqs79shWkis\r\n" \
    "JXVsjhT7OtZ8Ct1Nvc846MDfQXyi8VytlGIdGAGtJfWl36wlLiYYlTm5sOoAHNZz\r\n" \
    "mPwBS3T+17w24AqWx8YQrjVo2vNFyVY6NxDPj1FbaJK8HWR/EhDql9g6Vd8RmBil\r\n" \
    "JytFzEJLCopm+lc8Pcwv1KNmIBy9cLZzGt6CkVgHgobsHBTMabZwjbW7c7xjV5Jt\r\n" \
    "aeQSdabTrk+ZpDIQniK0mHQojUxlPNyLb00mSHo56VoxcVGgDPbAp68PxxIgtTfE\r\n" \
    "cJsCAwEAAaNQME4wHQYDVR0OBBYEFK5P96+nGXsLri55D7R75a6M9FQNMB8GA1Ud\r\n" \
    "IwQYMBaAFK5P96+nGXsLri55D7R75a6M9FQNMAwGA1UdEwQFMAMBAf8wDQYJKoZI\r\n" \
    "hvcNAQELBQADggEBAKu8p3lRlT71SkSrCLFandOesgWWFA40ioIzY1bKggLjEoGw\r\n" \
    "o079UpNEL21BgojkCXVNkFx63nna5DSBkopmHUNwTLYgUvUpPIBrEtt42XyWvanw\r\n" \
    "4XvOcT5dvB2SDgyxDxVJLKZaEuKXTKmZp9OcFV7jB4mgaq6YYbx4oau7Yrpy1G1P\r\n" \
    "HJY1y1ubZPQT2AKZVaKIPO6BUZkaZ7G4F4dm5cuCCQ8KURPQkXJ1S1AGH1Tgu1l9\r\n" \
    "7Arxz1A2NDpsi0GzFIuBiPWyMlxI0TFi2X3bDk6iCwS7B5PGI9CyRgiZUK50QnAF\r\n" \
    "F3Pog8oYk7jZIJdWwieklVukwD41YI/vNKaJ59E=\r\n" \
    "-----END CERTIFICATE-----"
};
/*
{
    \
    "-----BEGIN CERTIFICATE-----\r\n"
    "MIIDdTCCAl2gAwIBAgILBAAAAAABFUtaw5QwDQYJKoZIhvcNAQEFBQAwVzELMAkG\r\n" \
    "A1UEBhMCQkUxGTAXBgNVBAoTEEdsb2JhbFNpZ24gbnYtc2ExEDAOBgNVBAsTB1Jv\r\n" \
    "b3QgQ0ExGzAZBgNVBAMTEkdsb2JhbFNpZ24gUm9vdCBDQTAeFw05ODA5MDExMjAw\r\n" \
    "MDBaFw0yODAxMjgxMjAwMDBaMFcxCzAJBgNVBAYTAkJFMRkwFwYDVQQKExBHbG9i\r\n" \
    "YWxTaWduIG52LXNhMRAwDgYDVQQLEwdSb290IENBMRswGQYDVQQDExJHbG9iYWxT\r\n" \
    "aWduIFJvb3QgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDaDuaZ\r\n" \
    "jc6j40+Kfvvxi4Mla+pIH/EqsLmVEQS98GPR4mdmzxzdzxtIK+6NiY6arymAZavp\r\n" \
    "xy0Sy6scTHAHoT0KMM0VjU/43dSMUBUc71DuxC73/OlS8pF94G3VNTCOXkNz8kHp\r\n" \
    "1Wrjsok6Vjk4bwY8iGlbKk3Fp1S4bInMm/k8yuX9ifUSPJJ4ltbcdG6TRGHRjcdG\r\n" \
    "snUOhugZitVtbNV4FpWi6cgKOOvyJBNPc1STE4U6G7weNLWLBYy5d4ux2x8gkasJ\r\n" \
    "U26Qzns3dLlwR5EiUWMWea6xrkEmCMgZK9FGqkjWZCrXgzT/LCrBbBlDSgeF59N8\r\n" \
    "9iFo7+ryUp9/k5DPAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8E\r\n" \
    "BTADAQH/MB0GA1UdDgQWBBRge2YaRQ2XyolQL30EzTSo//z9SzANBgkqhkiG9w0B\r\n" \
    "AQUFAAOCAQEA1nPnfE920I2/7LqivjTFKDK1fPxsnCwrvQmeU79rXqoRSLblCKOz\r\n" \
    "yj1hTdNGCbM+w6DjY1Ub8rrvrTnhQ7k4o+YviiY776BQVvnGCv04zcQLcFGUl5gE\r\n" \
    "38NflNUVyRRBnMRddWQVDf9VMOyGj/8N7yy5Y0b2qvzfvGn9LhJIZJrglfCm7ymP\r\n" \
    "AbEVtQwdpf5pLGkkeB6zpxxxYu7KyJesF12KwvhHhm4qxFYxldBniYUr+WymXUad\r\n" \
    "DKqC5JlR3XC321Y9YeRq4VzW9v493kHMB65jUr9TU/Qr6cf9tveCX4XSQRjbgbME\r\n" \
    "HMUfpIBvFSDJ3gyICh3WZlXi/EjJKSZp4A==\r\n" \
    "-----END CERTIFICATE-----"
};
*/
